### ISSUE TITLE
install_github() gives Error in read.dcf(path)

### ISSUE THREAD

**Issue by sfirke** [r-lib/devtools#1900]
```
> devtools::install_github("adamMaier/reviewr")
Error in read.dcf(path) : 
  Found continuation line starting '    wrangling steps, ...' at begin of record.
```
That text "wrangling steps" comes from the DESCRIPTION file in the above repo.

This install command ran successfully in devtools 1.13.5, then I tried it under devtools 2.0.0 when it failed for my colleague and indeed it fails for me too under 2.0.0.  Nothing else changed between upgrading devtools so I expect this was introduced between 1.13.5 and 2.0.0.  I'm on Windows.

Looks similar to #709.

**Comment by jimhester** [comment]
The DESCRIPTION file in question is malformed, it has two `Depends` fields.

https://github.com/adamMaier/reviewr/blob/ae038d82a886a8316c4e6e44211a856d07285c8e/DESCRIPTION#L10

and

https://github.com/adamMaier/reviewr/blob/ae038d82a886a8316c4e6e44211a856d07285c8e/DESCRIPTION#L14

**Comment by adamMaier** [comment]
I fixed the two depends fields issues. But I was actually getting the same read.dcf error after that. I cut the number of spaces of indenting in the DESCRIPTION to 1 instead of 4, and that seemed to solve the issue.

**Comment by schuemie** [comment]
Voting to reopen this issue. I still get this error, but have a perfectly valid DESCRIPTION file (this example package happens to also live on CRAN, where there are no problems). I guess I might solve it by removing some extra spaces, but would hate to have to do that for all my prior Git tags. Code to reproduce the error:

```r
devtools::install_github("ohdsi/SqlRender", ref = "v1.5.3")
# Error in read.dcf(path) : 
#  Found continuation line starting '    person("Martijn" ...' at begin of record.
```

[Here](https://github.com/OHDSI/SqlRender/blob/c09f84e326df409640338f120939bcd1b5dba5d4/DESCRIPTION)'s the DESCRIPTION file at that tag. Session info:

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17      rstudioapi_0.7    magrittr_1.5      usethis_1.4.0     devtools_2.0.1    pkgload_1.0.2    
 [7] R6_2.2.2          rlang_0.2.1       tools_3.5.1       pkgbuild_1.0.2    sessioninfo_1.1.1 cli_1.0.0        
[13] withr_2.1.2       remotes_2.0.2     yaml_2.1.19       assertthat_0.2.0  digest_0.6.15     rprojroot_1.3-2  
[19] crayon_1.3.4      processx_3.1.0    callr_2.0.4       fs_1.2.6          curl_3.2          testthat_2.0.0   
[25] memoise_1.1.0     glue_1.2.0        compiler_3.5.1    desc_1.2.0        backports_1.1.2   prettyunits_1.0.2
```

**Comment by eaurele** [comment]
Same issue here, with a well-formed DESCRIPTION file ("ThinkR-open/shinytemplate"). Cloning and doing `remotes::install_local()` works though.

```r
> remotes::install_github("Thinkr-open/shinytemplate")
Error in read.dcf(path) : 
  Found continuation line starting '    R (>= 3.0) ...' at begin of record.
```

```bash
$ git clone git@github.com:ThinkR-open/shinytemplate.git
```

```r
> remotes::install_local()
These packages have more recent versions available.
Which would you like to update?

1:   jsonlite (1.5   -> 1.6  ) [CRAN]
2:   processx (3.2.0 -> 3.2.1) [CRAN]
3:   CRAN packages only
4:   All
5:   None

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 5
√  checking for file 'C:\Users\AureleMorovan\AppData\Local\Temp\RtmpQLVRJV\file38d4531863f1\shinytemplate/DESCRIPTION'
-  preparing 'shinytemplate':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'shinytemplate_0.0.21.tar.gz'
   
Installing package into ‘C:/Users/AureleMorovan/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'shinytemplate' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'shinytemplate'
    finding HTML links ... done
    create_shiny_template                   html  
    get_dependencies                        html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (shinytemplate)
In R CMD INSTALL
```

**Comment by kevinushey** [comment]
Technically duplicated fields are permitted in DESCRIPTION files:

``` r
read.dcf(textConnection("Foo: 1\nFoo: 2\n"))
#>      Foo
#> [1,] "2"
read.dcf(textConnection("Foo: 1\nFoo: 2\n"), all = TRUE)
#>    Foo
#> 1 1, 2
```

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pbr6cornell** [comment]
I am running into the same issue identified by @schuemie  and @eaurele .  My only recourse was to revert to older version of devtools.  But I dislike that 'solution', as I'd really like to keep up with all of the impressive work that this team is doing.  Can we relax the DESCRIPTION file reader to more gracefully handle spaces?

**Comment by schuemie** [comment]
Digging into this, I found this problem has been fixed [here in the `remotes` package](https://github.com/r-lib/remotes/commit/e56a41e1d0cad55cbe7d60b274b99ab7b7a76b5c). Until that makes it into CRAN, you can update remotes to the right point using
```r
devtools::install_github("r-lib/remotes", ref = "e56a41e1d0cad55cbe7d60b274b99ab7b7a76b5c")
```

**Comment by Nelson-Gon** [comment]
This seems to be due to indentation. At least that fixed it for me.
