### ISSUE TITLE
Error in devtools::check(): Error in if (force_suggests) lsuggests

### ISSUE THREAD

**Issue by rsetienne** [r-lib/devtools#1921]
Running devtools::check(), I get

-checking package dependencies ...Error in if (force_suggests) lsuggests
: (5.3s)missing value where TRUE/FALSE needed

**Comment by jimhester** [comment]
Sorry I cannot reproduce this, please provide an example package that reproduces this error with the current release of devtools.

**Comment by rsetienne** [comment]
Dear Jim,

Attached is the package that I am trying to check, and below is the 
result of check:

Cheers, Rampal

==> devtools::check(args = c('--timings','--as-cran')) Updating secsse 
documentation Writing NAMESPACE Loading secsse Registered S3 method 
overwritten by 'dplyr': method from as.data.frame.tbl_df tibble 
Registered S3 method overwritten by 'geiger': method from 
unique.multiPhylo ape Writing NAMESPACE 
--Building-----------------------------------------secsse--Setting env 
vars:* CFLAGS : -Wall -pedantic -fdiagnostics-color=always* CXXFLAGS : 
-Wall -pedantic -fdiagnostics-color=always* CXX11FLAGS: -Wall -pedantic 
-fdiagnostics-color=always---------------------------------------------------------------vchecking 
for file 'D:\data\Ms\SecSSE\secsse/DESCRIPTION'(615ms)-preparing 
'secsse':(1.1s)vchecking DESCRIPTION meta-information... - cleaning 
src-installing the package to build vignettes(451ms)vcreating 
vignettes(17s)-cleaning src-checking for LF line-endings in source and 
make files and shell scripts(414ms)-checking for empty or unneeded 
directories-looking to see if a 'data/datalist' file should be 
added-building 
'secsse_0.1.11.tar.gz'--Checking-----------------------------------------secsse--Setting 
env vars:* _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE* 
_R_CHECK_CRAN_INCOMING_REMOTE_ : FALSE* _R_CHECK_CRAN_INCOMING_ : FALSE* 
_R_CHECK_FORCE_SUGGESTS_ : FALSE-- R CMD check 
-----------------------------------------------------------------Warning 
in config_val_to_logical(Sys.getenv("_R_CHECK_FORCE_SUGGESTS_", : cannot 
coerce 'FALSE FALSE' to logical -using log directory 
'D:/data/Ms/SecSSE/secsse.Rcheck'- using R Under development (unstable) 
(2018-11-05 r75543)-using platform: x86_64-w64-mingw32 (64-bit)- using 
session charset: ISO8859-1-using options '--no-manual 
--as-cran'(678ms)vchecking for file 'secsse/DESCRIPTION'- this is 
package 'secsse' version '0.1.11'- package encoding: UTF-8vchecking 
package namespace information... -checking package dependencies ...Error 
in if (force_suggests) lsuggests : (3.7s)missing value where TRUE/FALSE 
needed Execution halted -- R CMD check results 
-------------------------------------- secsse 0.1.11 ----Duration: 5.5s 
0 errors v| 0 warnings v| 0 notes vR CMD check succeeded

**Comment by jimhester** [comment]
This is a duplicate of https://github.com/r-lib/devtools/issues/1914, see the workarounds in that issue until it is fixed.

**Comment by rsetienne** [comment]
Thanks. I would never have guessed that this is the same problem, though :-)

**Comment by rsetienne** [comment]
And I guess it isn't the same problem, because it persists even with the workaround check(incoming = NULL).

**Comment by jimhester** [comment]
It is fixed in the development version of devtools, please try that.

**Comment by rsetienne** [comment]
Dear Jim,

I installed it from GitHub yesterday and still the same error.

Cheers, Rampal
