### ISSUE TITLE
error when running devtools::install_deps('something', Ncpus = 2)

### ISSUE THREAD

**Issue by robkooper** [r-lib/devtools#2154]
When running `devtools::install_deps(Ncpus = 2)` it shows an error (see https://travis-ci.org/PecanProject/pecan/jobs/587707337#L2489).

```
Error: 1 components of `...` were not used.
We detected these problematic arguments:
* `Ncpus`
Did you misspecify an argument?
Backtrace:
    █
 1. └─devtools::install_deps(...)
 2.   └─(function (env = parent.frame(), action) ...
 3.     └─ellipsis:::action_dots(...)
Execution halted
Makefile:114: recipe for target '.doc/base/logger' failed
make: *** [.doc/base/logger] Error 1
The command "scripts/travis/script.sh" exited with 1.
```

I believe that internally it uses `install.packages` which does support the Ncpus argument. This used to work in the past, but now breaks the Travis builds. 

I'm basing this on the documentation found at: https://www.rdocumentation.org/packages/devtools/versions/2.2.0/topics/install_deps

**Comment by jimhester** [comment]
This should be fixed with the current CRAN version of devtools, you seem to be using an older version.

**Comment by infotroph** [comment]
@jimhester can you please have another look at this? I can still see the reported behavior both with devtools 2.2.1 from CRAN and with devtools master@568ac2a11 from GitHub.

**Comment by danarmak** [comment]
I'm seeing this too (in `install_dev_deps`). It happens only when all the deps are already installed and `install_deps` has nothing to do.
